// <auto-generated />
namespace Prodaja_i_Servis_Racunarske_Opreme.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MiG29 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MiG29));
        
        string IMigrationMetadata.Id
        {
            get { return "201807091947413_MiG29"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
