// <auto-generated />
namespace Prodaja_i_Servis_Racunarske_Opreme.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class M10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M10));
        
        string IMigrationMetadata.Id
        {
            get { return "201808042043599_M10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
